import { z } from 'zod';

/**
 * Base schema for position validation
 * Includes all fields from the Position model
 */
export const positionSchema = z.object({
  id: z.string().min(1, 'Position ID is required'),
  code: z.string().min(1, 'Position code is required'),
  name: z.string().min(1, 'Position name is required'),
  description: z.string().nullable().optional(),
  departmentId: z.string().min(1, 'Department ID is required'),
  minSalary: z
    .number()
    .positive('Minimum salary must be positive')
    .nullable()
    .optional(),
  maxSalary: z
    .number()
    .positive('Maximum salary must be positive')
    .nullable()
    .optional(),
  status: z.enum(['Active', 'Inactive'], {
    errorMap: () => ({ message: 'Status must be either Active or Inactive' }),
  }),
  createdAt: z.string().datetime().or(z.date()),
  updatedAt: z.string().datetime().or(z.date()),
  headCount: z.number().int('Head count must be an integer').optional(),
});

/**
 * Schema for creating a new position
 * Excludes id, createdAt, and updatedAt which are generated by the backend
 */
export const createPositionSchema = positionSchema.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

/**
 * Schema for updating an existing position
 * Same as create schema - doesn't include id or timestamps
 */
export const updatePositionSchema = createPositionSchema;

/**
 * Schema for position list items
 * Simplified version with minimal fields for display in lists
 */
export const positionListItemSchema = positionSchema.omit({
  description: true,
});

/**
 * Schema with salary range validation
 * Ensures maxSalary >= minSalary when both are provided
 */
export const positionWithSalaryValidationSchema = positionSchema.refine(
  (data) => {
    if (data.minSalary && data.maxSalary) {
      return data.maxSalary >= data.minSalary;
    }
    return true;
  },
  {
    message: 'Maximum salary must be greater than or equal to minimum salary',
    path: ['maxSalary'],
  },
);

/**
 * Type inference from schemas
 */
export type Position = z.infer<typeof positionSchema>;
export type CreatePositionInput = z.infer<typeof createPositionSchema>;
export type UpdatePositionInput = z.infer<typeof updatePositionSchema>;
export type PositionListItem = z.infer<typeof positionListItemSchema>;
