import { Department } from './department';
import { JobGrade } from './jobGrade';
import { Position } from './position';

export type EmploymentStatus =
  | 'Active'
  | 'Probation'
  | 'On Leave'
  | 'Suspended'
  | 'Resigned'
  | 'Terminated'
  | 'Retired';

export type EmploymentType =
  | 'Permanent'
  | 'Contract'
  | 'Probation'
  | 'Internship'
  | 'Part-Time';

export type Gender = 'Male' | 'Female';

export type MaritalStatus = 'Single' | 'Married' | 'Divorced' | 'Widowed';

export type BloodType = 'A' | 'B' | 'AB' | 'O';

export type EducationLevel =
  | 'High School'
  | 'Diploma'
  | 'Bachelor'
  | 'Master'
  | 'Doctorate'
  | 'Other';

export type Company = 'Koperasi' | 'MLP' | 'Outsource' | 'Other';

export type Religion =
  | 'Islam'
  | 'Kristen'
  | 'Katolik'
  | 'Hindu'
  | 'Buddha'
  | 'Konghucu'
  | 'Other';

export interface Employee {
  id: string;
  employeeNumber: string;
  nik: string;
  npwp?: string | null;

  // Personal info
  nickName: string;
  fullName: string;
  email: string;
  phone?: string | null;
  avatar?: string | null;
  gender: Gender;
  birthDate: Date;
  birthPlace: string;
  age: number;
  educationLevel?: EducationLevel | null;
  maritalStatus: MaritalStatus;
  bloodType?: BloodType | null;
  religion?: Religion | null;
  nationality: string;
  address?: string | null;

  // Employment info
  departmentId: string;
  positionId: string;
  jobGradeId?: string | null;
  managerId?: string | null;
  branchId?: string | null;
  status: EmploymentStatus;
  employmentType: EmploymentType;
  joinDate: Date;
  probationEndDate?: Date | null;
  resignDate?: Date | null;
  retireDate?: Date | null;
  company: Company;

  // Membership Info
  membershipNumber?: string | null;

  // Bank info
  bankName?: string | null;
  bankAccountNumber?: string | null;
  bankAccountName?: string | null;

  createdAt: Date;
  updatedAt: Date;

  // Relations
  department?: Department;
  position?: Position;
  jobGrade?: JobGrade;
  manager?: Employee;
}

// Mock data for development
export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    employeeNumber: 'EMP-001',
    nik: '3201010101800001',
    npwp: '12.345.678.9-001.000',
    nickName: 'Dewi',
    fullName: 'Dewi Lestari',
    email: 'dewi.lestari@company.com',
    phone: '081234567890',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Dewi+Lestari',
    gender: 'Female',
    birthDate: new Date('1985-03-15'),
    birthPlace: 'Bandung',
    age: 40,
    educationLevel: 'Master',
    maritalStatus: 'Married',
    bloodType: 'A',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Merdeka No. 10, Bandung',
    departmentId: 'dept-2',
    positionId: 'pos-1',
    jobGradeId: 'jg-4',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2019-01-18'),
    probationEndDate: null,
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BCA',
    bankAccountNumber: '1234567890',
    bankAccountName: 'Dewi Lestari',
    createdAt: new Date('2019-01-18'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-2',
    employeeNumber: 'EMP-002',
    nik: '3201010506750002',
    npwp: '98.765.432.1-002.000',
    nickName: 'Budi',
    fullName: 'Budi Santoso',
    email: 'budi.santoso@company.com',
    phone: '081298765432',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Budi+Santoso',
    gender: 'Male',
    birthDate: new Date('1975-06-05'),
    birthPlace: 'Jakarta',
    age: 50,
    educationLevel: 'Bachelor',
    maritalStatus: 'Married',
    bloodType: 'B',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Sudirman No. 25, Jakarta',
    departmentId: 'dept-3',
    positionId: 'pos-3',
    jobGradeId: 'jg-4',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2020-06-05'),
    probationEndDate: null,
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'Mandiri',
    bankAccountNumber: '9876543210',
    bankAccountName: 'Budi Santoso',
    createdAt: new Date('2020-06-05'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-3',
    employeeNumber: 'EMP-003',
    nik: '3201010312900003',
    nickName: 'Siti',
    fullName: 'Siti Rahayu',
    email: 'siti.rahayu@company.com',
    phone: '081311223344',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Siti+Rahayu',
    gender: 'Female',
    birthDate: new Date('1990-12-03'),
    birthPlace: 'Surabaya',
    age: 34,
    educationLevel: 'Bachelor',
    maritalStatus: 'Single',
    bloodType: 'O',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Pahlawan No. 7, Surabaya',
    departmentId: 'dept-2',
    positionId: 'pos-2',
    jobGradeId: 'jg-2',
    managerId: 'emp-1',
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2021-03-12'),
    probationEndDate: new Date('2021-06-12'),
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BNI',
    bankAccountNumber: '1122334455',
    bankAccountName: 'Siti Rahayu',
    createdAt: new Date('2021-03-12'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-4',
    employeeNumber: 'EMP-004',
    nik: '3201010708880004',
    npwp: '55.444.333.2-004.000',
    nickName: 'Ahmad',
    fullName: 'Ahmad Fauzi',
    email: 'ahmad.fauzi@company.com',
    phone: '081477889900',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Ahmad+Fauzi',
    gender: 'Male',
    birthDate: new Date('1988-07-08'),
    birthPlace: 'Yogyakarta',
    age: 36,
    educationLevel: 'Bachelor',
    maritalStatus: 'Married',
    bloodType: 'AB',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Malioboro No. 15, Yogyakarta',
    departmentId: 'dept-4',
    positionId: 'pos-6',
    jobGradeId: 'jg-4',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2018-09-01'),
    probationEndDate: null,
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BCA',
    bankAccountNumber: '5566778899',
    bankAccountName: 'Ahmad Fauzi',
    createdAt: new Date('2018-09-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-5',
    employeeNumber: 'EMP-005',
    nik: '3201010920950005',
    nickName: 'Rina',
    fullName: 'Rina Kartini',
    email: 'rina.kartini@company.com',
    phone: '081566778899',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Rina+Kartini',
    gender: 'Female',
    birthDate: new Date('1995-09-20'),
    birthPlace: 'Semarang',
    age: 29,
    educationLevel: 'Bachelor',
    maritalStatus: 'Single',
    bloodType: 'A',
    religion: 'Kristen',
    nationality: 'Indonesian',
    address: 'Jl. Pemuda No. 33, Semarang',
    departmentId: 'dept-5',
    positionId: 'pos-7',
    jobGradeId: 'jg-4',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2022-04-01'),
    probationEndDate: new Date('2022-07-01'),
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'Mandiri',
    bankAccountNumber: '6677889900',
    bankAccountName: 'Rina Kartini',
    createdAt: new Date('2022-04-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-6',
    employeeNumber: 'EMP-006',
    nik: '3201011511870006',
    npwp: '77.888.999.0-006.000',
    nickName: 'Hendra',
    fullName: 'Hendra Wijaya',
    email: 'hendra.wijaya@company.com',
    phone: '081655443322',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Hendra+Wijaya',
    gender: 'Male',
    birthDate: new Date('1987-11-15'),
    birthPlace: 'Medan',
    age: 37,
    educationLevel: 'Bachelor',
    maritalStatus: 'Married',
    bloodType: 'B',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Gatot Subroto No. 42, Medan',
    departmentId: 'dept-6',
    positionId: 'pos-8',
    jobGradeId: 'jg-4',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2017-07-03'),
    probationEndDate: null,
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BRI',
    bankAccountNumber: '7788990011',
    bankAccountName: 'Hendra Wijaya',
    createdAt: new Date('2017-07-03'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-7',
    employeeNumber: 'EMP-007',
    nik: '3201010205920007',
    nickName: 'Maya',
    fullName: 'Maya Putri',
    email: 'maya.putri@company.com',
    phone: '081799001122',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Maya+Putri',
    gender: 'Female',
    birthDate: new Date('1992-05-02'),
    birthPlace: 'Denpasar',
    age: 32,
    educationLevel: 'Bachelor',
    maritalStatus: 'Single',
    bloodType: 'O',
    religion: 'Hindu',
    nationality: 'Indonesian',
    address: 'Jl. Raya Kuta No. 8, Denpasar',
    departmentId: 'dept-4',
    positionId: 'pos-5',
    jobGradeId: 'jg-3',
    managerId: 'emp-4',
    status: 'Active',
    employmentType: 'Contract',
    joinDate: new Date('2023-01-02'),
    probationEndDate: new Date('2023-04-02'),
    resignDate: null,
    retireDate: null,
    company: 'Outsource',
    bankName: 'BCA',
    bankAccountNumber: '8899001122',
    bankAccountName: 'Maya Putri',
    createdAt: new Date('2023-01-02'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-8',
    employeeNumber: 'EMP-008',
    nik: '3201011001930008',
    nickName: 'Rizki',
    fullName: 'Rizki Pratama',
    email: 'rizki.pratama@company.com',
    phone: '081811223344',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Rizki+Pratama',
    gender: 'Male',
    birthDate: new Date('1993-10-10'),
    birthPlace: 'Makassar',
    age: 31,
    educationLevel: 'Bachelor',
    maritalStatus: 'Single',
    bloodType: 'A',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Sultan Hasanuddin No. 5, Makassar',
    departmentId: 'dept-3',
    positionId: 'pos-4',
    jobGradeId: 'jg-2',
    managerId: 'emp-2',
    status: 'Probation',
    employmentType: 'Probation',
    joinDate: new Date('2026-04-01'),
    probationEndDate: new Date('2026-07-01'),
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BNI',
    bankAccountNumber: '9900112233',
    bankAccountName: 'Rizki Pratama',
    createdAt: new Date('2026-04-01'),
    updatedAt: new Date('2026-04-01'),
  },
  {
    id: 'emp-9',
    employeeNumber: 'EMP-009',
    nik: '3201010302850009',
    npwp: '33.222.111.0-009.000',
    nickName: 'Agus',
    fullName: 'Agus Setiawan',
    email: 'agus.setiawan@company.com',
    phone: '081922334455',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Agus+Setiawan',
    gender: 'Male',
    birthDate: new Date('1985-02-03'),
    birthPlace: 'Solo',
    age: 41,
    educationLevel: 'Bachelor',
    maritalStatus: 'Married',
    bloodType: 'A',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Slamet Riyadi No. 21, Solo',
    departmentId: 'dept-1',
    positionId: 'pos-9',
    jobGradeId: 'jg-4',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2016-03-01'),
    probationEndDate: null,
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BCA',
    bankAccountNumber: '1023456789',
    bankAccountName: 'Agus Setiawan',
    createdAt: new Date('2016-03-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-10',
    employeeNumber: 'EMP-010',
    nik: '3201011407910010',
    nickName: 'Fitri',
    fullName: 'Fitri Handayani',
    email: 'fitri.handayani@company.com',
    phone: '082033445566',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Fitri+Handayani',
    gender: 'Female',
    birthDate: new Date('1991-07-14'),
    birthPlace: 'Palembang',
    age: 34,
    educationLevel: 'Bachelor',
    maritalStatus: 'Married',
    bloodType: 'B',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Jend. Sudirman No. 55, Palembang',
    departmentId: 'dept-2',
    positionId: 'pos-2',
    jobGradeId: 'jg-2',
    managerId: 'emp-1',
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2020-08-10'),
    probationEndDate: new Date('2020-11-10'),
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'Mandiri',
    bankAccountNumber: '2034567890',
    bankAccountName: 'Fitri Handayani',
    createdAt: new Date('2020-08-10'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-11',
    employeeNumber: 'EMP-011',
    nik: '3201010609940011',
    nickName: 'Dimas',
    fullName: 'Dimas Prasetyo',
    email: 'dimas.prasetyo@company.com',
    phone: '082144556677',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Dimas+Prasetyo',
    gender: 'Male',
    birthDate: new Date('1994-09-06'),
    birthPlace: 'Malang',
    age: 31,
    educationLevel: 'Bachelor',
    maritalStatus: 'Single',
    bloodType: 'O',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Ijen No. 12, Malang',
    departmentId: 'dept-5',
    positionId: 'pos-7',
    jobGradeId: 'jg-3',
    managerId: 'emp-5',
    status: 'Active',
    employmentType: 'Contract',
    joinDate: new Date('2024-02-15'),
    probationEndDate: new Date('2024-05-15'),
    resignDate: null,
    retireDate: null,
    company: 'Outsource',
    bankName: 'BNI',
    bankAccountNumber: '3045678901',
    bankAccountName: 'Dimas Prasetyo',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'emp-12',
    employeeNumber: 'EMP-012',
    nik: '3201012012960012',
    nickName: 'Laras',
    fullName: 'Laras Indah',
    email: 'laras.indah@company.com',
    phone: '082255667788',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Laras+Indah',
    gender: 'Female',
    birthDate: new Date('1996-12-20'),
    birthPlace: 'Bogor',
    age: 29,
    educationLevel: 'Diploma',
    maritalStatus: 'Single',
    bloodType: 'AB',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Pajajaran No. 30, Bogor',
    departmentId: 'dept-3',
    positionId: 'pos-4',
    jobGradeId: 'jg-1',
    managerId: 'emp-2',
    status: 'Probation',
    employmentType: 'Probation',
    joinDate: new Date('2026-03-01'),
    probationEndDate: new Date('2026-06-01'),
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BCA',
    bankAccountNumber: '4056789012',
    bankAccountName: 'Laras Indah',
    createdAt: new Date('2026-03-01'),
    updatedAt: new Date('2026-03-01'),
  },
  {
    id: 'emp-13',
    employeeNumber: 'EMP-013',
    nik: '3201010801800013',
    npwp: '44.333.222.1-013.000',
    nickName: 'Wahyu',
    fullName: 'Wahyu Nugroho',
    email: 'wahyu.nugroho@company.com',
    phone: '082366778899',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Wahyu+Nugroho',
    gender: 'Male',
    birthDate: new Date('1980-01-08'),
    birthPlace: 'Purwokerto',
    age: 46,
    educationLevel: 'Master',
    maritalStatus: 'Married',
    bloodType: 'A',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Jend. Soedirman No. 88, Purwokerto',
    departmentId: 'dept-1',
    positionId: 'pos-10',
    jobGradeId: 'jg-5',
    managerId: null,
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2010-05-01'),
    probationEndDate: null,
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'Mandiri',
    bankAccountNumber: '5067890123',
    bankAccountName: 'Wahyu Nugroho',
    createdAt: new Date('2010-05-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-14',
    employeeNumber: 'EMP-014',
    nik: '3201011503980014',
    nickName: 'Nadia',
    fullName: 'Nadia Permata',
    email: 'nadia.permata@company.com',
    phone: '082477889900',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Nadia+Permata',
    gender: 'Female',
    birthDate: new Date('1998-03-15'),
    birthPlace: 'Tangerang',
    age: 28,
    educationLevel: 'Bachelor',
    maritalStatus: 'Single',
    bloodType: 'B',
    religion: 'Kristen',
    nationality: 'Indonesian',
    address: 'Jl. MH Thamrin No. 17, Tangerang',
    departmentId: 'dept-6',
    positionId: 'pos-8',
    jobGradeId: 'jg-2',
    managerId: 'emp-6',
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2023-07-17'),
    probationEndDate: new Date('2023-10-17'),
    resignDate: null,
    retireDate: null,
    company: 'MLP',
    bankName: 'BRI',
    bankAccountNumber: '6078901234',
    bankAccountName: 'Nadia Permata',
    createdAt: new Date('2023-07-17'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'emp-15',
    employeeNumber: 'EMP-015',
    nik: '3201012511890015',
    npwp: '66.555.444.3-015.000',
    nickName: 'Yusuf',
    fullName: 'Yusuf Hakim',
    email: 'yusuf.hakim@company.com',
    phone: '082588990011',
    avatar: 'https://api.dicebear.com/9.x/initials/svg?seed=Yusuf+Hakim',
    gender: 'Male',
    birthDate: new Date('1989-11-25'),
    birthPlace: 'Balikpapan',
    age: 36,
    educationLevel: 'Bachelor',
    maritalStatus: 'Married',
    bloodType: 'O',
    religion: 'Islam',
    nationality: 'Indonesian',
    address: 'Jl. Jend. Sudirman No. 64, Balikpapan',
    departmentId: 'dept-4',
    positionId: 'pos-5',
    jobGradeId: 'jg-3',
    managerId: 'emp-4',
    status: 'Active',
    employmentType: 'Permanent',
    joinDate: new Date('2019-11-01'),
    probationEndDate: new Date('2020-02-01'),
    resignDate: null,
    retireDate: null,
    company: 'Koperasi',
    bankName: 'BNI',
    bankAccountNumber: '7089012345',
    bankAccountName: 'Yusuf Hakim',
    createdAt: new Date('2019-11-01'),
    updatedAt: new Date('2024-01-01'),
  },
];
